version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
       - db-data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: minio server /data -console-address ":9001"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  init:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  webserver:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    command: webserver

  scheduler:
    build: .
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    command: scheduler

volumes:
  logs:
  dags:
  data:
  db-data:
