version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    env_file:
      - .env
    command: minio server /data --console-address ":9001"

  init:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    command: webserver

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    env_file:
      - .env
    command: scheduler

volumes:
  logs:
  data: