version: 1
formatters:
  simple:
    format: '%(asctime)s - %(message)s'
    datefmt: '%d.%m.%Y %H:%M'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: game.log
root:
  level: DEBUG
  handlers: [console, file]